projeto/projeto/urls.py
from django.contrib import admin
from django.urls import path
from app import views

urlpatterns = [
    path('', views.log, name='login'),
    path('login_responsavel/', views.loginPai, name='login_pai'),
    path('login_professor/', views.loginProfessor, name='login_professor'),
    path('admin/', admin.site.urls),
    path('responsavel/', views.homePai, name='home_pai'),
    path('home_professor/', views.homeProfessor, name='home_professor'),
    path('cadastrar_notas/<int:simulado_id>/', views.cadastrar_notas, name='cadastrar_notas'), # Corrigido aqui
    path('cadastrar_turma/', views.cadastrar_turma, name='cadastrar_turma'),
    path('cadastrar_aluno/<int:id>', views.cadastrar_aluno, name='cadastrar_aluno'),
    path('turmas/', views.turmas, name='turmas'),
    path('alunos/<int:id>', views.alunos, name='alunos')
]

projeto/app/models.py
from django.db import models
from django.contrib.auth.models import User

# Classe Professor
class Professor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='professor', default=None)

    def cadastrar_nota(self, simulado, aluno, nota_portugues, nota_matematica):
        Nota.objects.create(
            aluno=aluno,
            simulado=simulado,
            nota_portugues=nota_portugues,
            nota_matematica=nota_matematica
        )

    def editar_nota(self, nota, nova_nota_portugues, nova_nota_matematica):
        nota.nota_portugues = nova_nota_portugues
        nota.nota_matematica = nova_nota_matematica
        nota.save()

    def visualizar_alunos(self, turma):
        return turma.alunos.all()

# Classe Simulado

class Simulado(models.Model):
    nome = models.CharField(max_length=100)
    alunos = models.ManyToManyField('Aluno', related_name='simulados')
    peso_matematica = models.FloatField()
    peso_portugues = models.FloatField()

    def calcular_nota(self, aluno):
        
        #Calcula a nota ponderada de um aluno no simulado.
        
        try:
            nota = Nota.objects.get(aluno=aluno, simulado=self)
            total_peso = self.peso_matematica + self.peso_portugues
            return (
                (nota.nota_matematica * self.peso_matematica) +
                (nota.nota_portugues * self.peso_portugues)
            ) / total_peso
        except Nota.DoesNotExist:
            return None

# Classe Turma
class Turma(models.Model):
    nome_turma = models.CharField(max_length=100)
    professor = models.ManyToManyField(Professor, related_name='turmas', null=True)
    simulados = models.ManyToManyField(Simulado, related_name='turmas', null=True, blank=True)

    def ordenar_notas(self):
        """
        Ordena os alunos da turma pelo nome.
        """
        return sorted(self.alunos.all(), key=lambda aluno: aluno.nome)

    def calcular_media(self):
        """
        Calcula a média geral das notas dos alunos da turma.
        """
        alunos = self.alunos.all()
        notas = Nota.objects.filter(aluno__in=alunos)
        total_notas = sum((nota.nota_portugues or 0) + (nota.nota_matematica or 0) for nota in notas)
        num_notas = notas.count() * 2  # Português e Matemática
        return total_notas / num_notas if num_notas > 0 else 0


# Classe Aluno
class Aluno(models.Model):
    nome = models.CharField(max_length=100)
    data_de_nascimento = models.DateField()
    sexo = models.CharField(max_length=1, choices=[('M', 'Masculino'), ('F', 'Feminino')])
    turma = models.ForeignKey(Turma, on_delete=models.CASCADE, related_name='alunos')

# Classe Pai
class Pai(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='pai')
    alunos = models.ManyToManyField(Aluno, related_name='pais')

# Classe Nota
class Nota(models.Model):
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE)
    simulado = models.ForeignKey(Simulado, on_delete=models.CASCADE, null=True)
    nota_portugues = models.FloatField(null=True, blank=True)
    nota_matematica = models.FloatField(null=True, blank=True)


# Classe Tema
class Tema(models.Model):
    nome = models.CharField(max_length=100)
    questoes_dificeis = models.IntegerField()
    questoes_faceis = models.IntegerField()
    

projeto/app/templates/alunos.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="PT-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{turma.nome_turma}}</title>
  <link rel="stylesheet" href="{% static '/css/turmas.css' %}" type="text/css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</head>
<body class="custom-bg d-flex flex-column justify-content-center align-items-center vh-100">
    <div style="text-align: center;"><img src="{% static 'imagens/Logo.png' %}"  alt="logo cesar" width="240px" style="padding-top: 10px;"></div>

    <div class="turma-container">
        <div class="header">
            <span>{{alunos.count}} alunos</span>
        </div>
    
        <h2>{{turma.nome_turma}}</h2>
    
        <!-- Tabela de Alunos -->
        <table class="alunos-tabela">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Nascimento</th>
                    <th>Turma</th>
                    <th>Sexo</th>
                </tr>
            </thead>
            <tbody>
                {% for aluno in alunos %}
                <tr>
                    <td>{{ aluno.nome }}</td>
                    <td>{{ aluno.data_de_nascimento }}</td>
                    <td>{{ aluno.turma.nome_turma }}</td>
                    <td>{{ aluno.sexo }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">Nenhum aluno cadastrado.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    
        <!-- Botão para adicionar aluno -->
        <div class="add-aluno">
            <button onclick="window.location.href='{% url 'cadastrar_aluno' turma.id %}'">+</button>
        </div>
    </div>    
</body>
</html>

projeto/app/templates/cadastrar_aluno.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="PT-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cadastrar Aluno</title>
  <link rel="stylesheet" href="{% static '/css/style.css' %}" type="text/css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</head>

<body class="custom-bg d-flex flex-column justify-content-center align-items-center vh-100">
  <div style="text-align: center;"><img src="{% static 'imagens/Logo.png' %}"  alt="logo cesar" width="240px" style="padding-top: 10px;"></div>
  
  <div class=" container-fluid d-flex justify-content-center align-items-center vh-100">
    <form class="login-form" method="POST" action="{% url 'cadastrar_aluno' turma.id %}">
        
      {% csrf_token %}
      <div class="mb-3">
        <label class="form-label ">Nome do Aluno:</label>
        <div class="form-text-input"> 
        <input type="text" id="nome" class="form-control form-input" name="nome" required placeholder="Digite o nome do aluno">
      </div>
    </div>
    <div class="mb-3">
        <label class="form-label ">Data de Nascimento:</label>
        <input type="date" id="data_de_nascimento" class="form-control form-input" name="data_de_nascimento" required>
      </div>
      <div class="mb-3">
        <label class="form-label ">Sexo:</label>
        <select id="sexo" class="form-control form-input" name="sexo" required>
            <option value="M">Masculino</option>
            <option value="F">Feminino</option>
        </select><br>
      </div>
      <div class="login-button">
      <input type="submit" class="btn btn-primary grade-button" value="Cadastrar" name="entrar">
      </div>
    
      {% if messages %}
      {% for message in messages %}
        {% if message.tags == 'success' %}
          <div class="alert alert-success" role="alert">{{ message }}</div>
        {% else %}
          <div class="alert alert-danger" role="alert">{{ message }}</div>
        {% endif %}
      {% endfor %}
      {% endif %}
    </form>
  </div>


</body>
</html>

projeto/app/templates/cadastrar_notas.html
{% block content %}
    <h1>{{ simulado.nome }}</h1>

<form method="post">
    {% csrf_token %}
    <table>
        <tr>
            <th>Aluno</th>
            <th>Nota Português</th>
            <th>Nota Matemática</th>
        </tr>
        {% for aluno in alunos %}
        <tr>
            <td>{{ aluno.nome }}</td>
            <td><input type="text" name="nota_portugues_{{ aluno.id }}" /></td>
            <td><input type="text" name="nota_matematica_{{ aluno.id }}" /></td>
        </tr>
        {% endfor %}
    </table>
    <button type="submit">Cadastrar Notas</button>
</form>
{% endblock content %}

projeto/app/templates/cadastrar_simulados.html
{% load static %}
{% load i18n %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/cadastrar_atividade.css' %}" type="text/css">
    
    <header>
        <h1 class="text-center white-color">Cadastrar <span class="orange-text">Atividades</span></h1>
    </header>
    <form action="{% url 'cadastrar_atividades_professor' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% if messages %}
            {% for message in messages %}
                <p class="{{ message.tags }}">
                    {{ message }}
                </p>
            {% endfor %}
        {% endif %}

        <select name="turma">
            {% for turma in turmas %}
                <option value="{{turma.nome}}">
                    {{turma.nome}}
                </option>
            {% endfor %}
        </select>
        <select name="disciplina">
            {% for disciplina in disciplinas %}
                <option value="{{disciplina.nome}}">
                    {{disciplina.nome}}
                </option>
            {% endfor %}
        </select>
        <input type="text" name="titulo" placeholder="Título da atividade..." class="white-color" value="{{request.POST.titulo}}">
        <textarea name="texto" id="" placeholder="Descrição da atividade..." 
        class="white-color" cols="60" rows="5"  value="{{request.POST.titulo}}"></textarea>
        <input type="file" name="arquivo" class="white-color">
        <input type="submit" value="Cadastrar atividade">
    </form>

{% endblock content %}

projeto/app/templates/cadastrar_turma.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="PT-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cadastrar Turma</title>
  <link rel="stylesheet" href="{% static '/css/style.css' %}" type="text/css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</head>

<body class="custom-bg d-flex flex-column justify-content-center align-items-center vh-100">
  <div style="text-align: center;"><img src="{% static 'imagens/Logo.png' %}"  alt="logo cesar" width="240px" style="padding-top: 10px;"></div>
  
  <div class=" container-fluid d-flex justify-content-center align-items-center vh-100">
    <form class="login-form" method="POST" action="{% url 'cadastrar_turma' %}">
      {% csrf_token %}
      <div class="mb-3">

        <label class="form-label ">Nome da Turma:</label>
        <div class="form-text-input"> 
        <input type="text" id="nome_turma" class="form-control form-input" name="nome_turma" required placeholder="Digite o nome da turma">
      </div>
      </div>

      <div class="login-button">
      <input type="submit" class="btn btn-primary grade-button" value="Cadastrar" name="entrar">
      </div>
    
      {% if messages %}
      {% for message in messages %}
        {% if message.tags == 'success' %}
          <div class="alert alert-success" role="alert">{{ message }}</div>
        {% else %}
          <div class="alert alert-danger" role="alert">{{ message }}</div>
        {% endif %}
      {% endfor %}
      {% endif %}
    </form>
  </div>
</body>
</html>

projeto/app/templates/cadastro.html
{%load static %}
{%load i18n %}
<!DOCTYPE html>
<html lang="PT-BR">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
crossorigin="anonymous"></script>
<!------------------------------------------------------------------------------------------------------------------------>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% trans "Cadastro" %}</title>
  <link rel="stylesheet" href="{% static '/css/style.css' %}" type="text/css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<!------------------------------------------------------------------------------------------------------------------------>

<body class="custom-bg d-flex flex-column justify-content-center align-items-center vh-100">
  <div style="text-align: center"><img src="{% static 'images/white-cesar.png' %}"  alt="logo cesar"></div>
  <br>
  <br>
<br>
  <div class="container-fluid d-flex justify-content-center align-items-center vh-100" >
    <form class="login-form" method="post">
      {% csrf_token %}
<!-------------------------------------------------------------------------------------------------------------------------------------->        
<div class="form-text-input">
      <div class="mb-3">
        <label class="form-label">{% trans "Formulário" %}</label>
        <br>
        <input type='text' name='username' class="form-control" required placeholder='Nome de usuário'>
<!-------------------------------------------------------------------------------------------------------------------------------------->        

        <br>
        <input type="email" class="form-control" name="email" 
          placeholder="Digite o email" required>
      </div>
<!-------------------------------------------------------------------------------------------------------------------------------------->        

      <div class="mb-3">
        <label class="form-label">{% trans "Senha" %}</label>
        <input type="password" class="form-control"  name="senha" placeholder="Digite a senha" required>
      </div>

<!-------------------------------------------------------------------------------------------------------------------------------------->        

      <label for="user-type" >{% trans "Escolha seu papel:" %}</label>
        <select id="user-type" name="user_type" class="form-control"> 
            <option value="professor">{% trans "Professor" %}</option>
            <option value="aluno">{% trans "Aluno" %}</option>
        </select>
      </div>
<!-------------------------------------------------------------------------------------------------------------------------------------->        
<br>
      <div class="login-button" >
      <input type="submit" class="btn btn-primary " value="Cadastrar">
        </div>
        <br>
        {% trans "Ja tem uma conta? faça" %} <a href="{% url 'login' %}">Login</a>
<!-------------------------------------------------------------------------------------------------------------------------------------->        

        {% if messages %}
        {% for message in messages %}
          {% if message.tags == 'success' %}
            <div class="alert alert-success" role="alert">{{ message }}</div> <!-- Exibe alerta verde -->
          {% else %}
            <div class="alert alert-danger" role="alert">{{ message }}</div> <!-- Exibe alerta vermelho -->
          {% endif %}
        {% endfor %}
      {% endif %}
<!-------------------------------------------------------------------------------------------------------------------------------------->        

      
    </form>
  </div>

  

</body>

</html>

projeto/app/templates/home_professor.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="PT-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home Professor</title>
  <link rel="stylesheet" href="{% static '/css/style.css' %}" type="text/css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</head>

<body class="custom-bg d-flex flex-column justify-content-center align-items-center vh-100">
    <div style="text-align: center;">
        <img src="{% static 'imagens/Logo.png' %}" alt="logo cesar" width="240px" style="padding-top: 10px;">
    </div>

    <!-- Menu com botões -->
    <div class="container d-flex flex-column justify-content-center align-items-center">
        <div class="menu-box text-center">
            <h1 class="menu-title">Menu</h1>
            <div class="menu-buttons">
                <form action="{% url 'home_professor' %}" method="POST">
                    {% csrf_token %}
                    <!-- Botão Turmas -->
                    <button  class="btn btn-primary menu-button" name="turmas">Turmas</button>
                    <!-- Botão Simulados -->
                    <button  class="btn btn-primary menu-button" name="simulados">Simulados</button>
                </form>
            </div>
        </div>
    </div>
</body>

projeto/app/templates/login.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="PT-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <link rel="stylesheet" href="{% static '/css/style.css' %}" type="text/css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</head>

<body class="custom-bg d-flex flex-column justify-content-center align-items-center vh-100">
  <div style="text-align: center;"><img src="{% static 'imagens/Logo.png' %}"  alt="logo cesar" width="240px" style="padding-top: 10px;"></div>
  <style>
    .grade-button {
      width: 120px;
      height: 40px;
      color: white;
      margin-top: 10px;  
      border-radius: 10%;
      background-color: #1d30d8;
      border: none;
      font-weight: 600;
      display: flex;
      align-items: center;
      justify-content: center;
      box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.164);
      cursor: pointer;
      transition-duration: 0.3s;
      overflow: hidden;
      position: relative;
      text-decoration: none !important;
    }
    
    .grade-button:hover {
      width: 120px;
      border-radius: 50px;
      transition-duration: 0.3s;
      align-items: center;
    }
  </style>
  <div class=" container-fluid d-flex justify-content-center align-items-center vh-100">
 
    <div>
        <form method = "POST">
            {% csrf_token %}
            <button type="submit" name = "pai" class="grade-button">Responsável</button>
        </form>
        <form method = "POST">
            {% csrf_token %}
            <button type="submit" name = "professor" class="grade-button">professor</button>
        </form>
    </div>
  </div>

  <footer class="container-fluid text-center" style="padding-bottom: 10px; background-color: #1d30d8; color: white; bottom: -200; width: 100%;">
    <p>Para motivos de avaliação, deixamos uma conta com de professores. OBS: a senhas são 123.<br>
      Professores: Pedro Sampaio.<br>
      Parente: João Paula
    </p>

  </footer>
</body>
</html>

projeto/app/templates/login_pai.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="PT-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <link rel="stylesheet" href="{% static '/css/style.css' %}" type="text/css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</head>

<body class="custom-bg d-flex flex-column justify-content-center align-items-center vh-100">
  <div style="text-align: center;"><img src="{% static 'imagens/Logo.png' %}"  alt="logo cesar" width="240px" style="padding-top: 10px;"></div>
  
  <div class=" container-fluid d-flex justify-content-center align-items-center vh-100">
    <form class="login-form" method="POST" action="{% url 'login' %}">
      {% csrf_token %}
      <div class="mb-3">

        <label class="form-label ">Usuário</label>
        <div class="form-text-input"> 
        <input type="text" id="login-input" class="form-control form-input" name="username" required placeholder="Digite o nome de usuário">
      </div>
      </div>

      <div class="mb-3">
        <label class="form-label">Senha</label>
        <div class="form-text-input"> 
        <input id="password-input" type="password" class="form-control"  name="senha" placeholder="Digite a senha"  required>
        </div>
      </div>

      <div class="login-button">
      <input type="submit" class="btn btn-primary grade-button" value="Entrar">
      </div>

      <div class="register-link text-center">
        Ainda não tem uma conta? Registrar-se
      </div>
    
      {% if messages %}
      {% for message in messages %}
        {% if message.tags == 'success' %}
          <div class="alert alert-success" role="alert">{{ message }}</div>
        {% else %}
          <div class="alert alert-danger" role="alert">{{ message }}</div>
        {% endif %}
      {% endfor %}
      {% endif %}
    </form>
  </div>

</body>
</html>

projeto/app/templates/login_professor.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="PT-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <link rel="stylesheet" href="{% static '/css/style.css' %}" type="text/css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</head>

<body class="custom-bg d-flex flex-column justify-content-center align-items-center vh-100">
  <div style="text-align: center;"><img src="{% static 'imagens/Logo.png' %}"  alt="logo cesar" width="240px" style="padding-top: 10px;"></div>
  
  <div class=" container-fluid d-flex justify-content-center align-items-center vh-100">
    <form class="login-form" method="POST" action="{% url 'login_professor' %}">
      {% csrf_token %}
      <div class="mb-3">

        <label class="form-label ">Usuário</label>
        <div class="form-text-input"> 
        <input type="text" id="login-input" class="form-control form-input" name="nome" required placeholder="Digite o nome de usuário">
      </div>
      </div>

      <div class="mb-3">
        <label class="form-label">Senha</label>
        <div class="form-text-input"> 
        <input id="password-input" type="password" class="form-control"  name="senha" placeholder="Digite a senha"  required>
        </div>
      </div>

      <div class="login-button">
      <input type="submit" class="btn btn-primary grade-button" value="Entrar" name="entrar">
      </div>
    
      {% if messages %}
      {% for message in messages %}
        {% if message.tags == 'success' %}
          <div class="alert alert-success" role="alert">{{ message }}</div>
        {% else %}
          <div class="alert alert-danger" role="alert">{{ message }}</div>
        {% endif %}
      {% endfor %}
      {% endif %}
    </form>
  </div>


</body>
</html>

projeto/app/templates/perfilaluno.html
{% load static %}
{% block content%}

<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/buttons.css' %}">

<div class="main-content">
    <h1>Perfil do Pai: {{ pai.nome }}</h1>

    <h2>Filhos:</h2>
    <ul>
        {% for aluno in alunos %}
            <li>
                <strong>Nome:</strong> {{ aluno.nome }}<br>
                <strong>Data de Nascimento:</strong> {{ aluno.data_de_nascimento }}<br>
                <strong>Idade:</strong> {{ aluno.idade }}<br>
                <strong>Sexo:</strong> {{ aluno.get_sexo_display }}<br>
            </li>
        {% empty %}
            <p>Não há filhos cadastrados para este pai.</p>
        {% endfor %}
    </ul>
</div>
{% endblock %}